############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "/about"
weight = 2

[[main]]
name = "Services"
url = "/services"
weight = 3


[[main]]
name = "Contact"
url = "/contact"



# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About Us"
url = "/about/"
weight = 2

[[footer]]
name = "Services"
url = "/services"
weight = 3

[[footer]]
name = "Contact Us"
url = "/contact"
weight = 4
